In [3]:
import numpy as np

**creating a 1D array from a list**

In [6]:
sales_list = [120, 150, 300, 250, 90]
sales_array = np.array(sales_list)
print(sales_list)
print(sales_array)

[120, 150, 300, 250, 90]
[120 150 300 250  90]


**creating a 2D array from a list of lists**

In [11]:
# features: [age, income_in_k, credit_score]

customer_matrix = np.array([[25, 50, 710],
                            [41, 95, 780],
                            [32, 65, 620]])

print(customer_matrix)
print("Customer matrix shape:", customer_matrix.shape)

[[ 25  50 710]
 [ 41  95 780]
 [ 32  65 620]]
Customer matrix shape: (3, 3)


**creating a matrix of zeros**

In [ ]:
zero_matrix = np.zeros((3, 4))
print(zero_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Arange function to create a sequenced array**

In [10]:
sequenced_array = np.arange(0,10,2)
print(sequenced_array)

[0 2 4 6 8]


**Slicing a 1D array**

In [13]:
traffic = np.array([500, 600, 550, 700, 650, 900, 1100])
weekend_traffic = traffic[-2:]
print(weekend_traffic)

[ 900 1100]


**Setup a 2D array to represent sensor readings**

In [ ]:
sensors = np.array([
            [12.1,14.3,15.2],#sensor 0
            [11.5,13.8,14.9],#sensor 1
            [10.8,12.5,13.7],#sensor 2
            [9.5,11.2,12.4] #sensor 3
        ])

In [16]:
sensors

array([[12.1, 14.3, 15.2],
       [11.5, 13.8, 14.9],
       [10.8, 12.5, 13.7],
       [ 9.5, 11.2, 12.4]])

In [19]:
specific_reading = sensors[2, 1]
print(specific_reading)

12.5


In [20]:
top_sensors = sensors[0:2, :]
print(top_sensors)

[[12.1 14.3 15.2]
 [11.5 13.8 14.9]]


In [22]:
final_reading = sensors[:, 2]
print(final_reading)

[15.2 14.9 13.7 12.4]


**Reshaping Example**

In [26]:
flat_temps = np.array([22, 24, 19, 21, 23, 20, 25, 18, 22, 24, 18, 21]) # temperatures in celsius.
# reshape into 4 day, 3 readings per day
reshaped_temps = flat_temps.reshape(4, 3)
print(reshaped_temps)

[[22 24 19]
 [21 23 20]
 [25 18 22]
 [24 18 21]]


**Broadcasting Example**

In [27]:
farenheit_temps = (reshaped_temps * 9/5) + 32
print(farenheit_temps)

[[71.6 75.2 66.2]
 [69.8 73.4 68. ]
 [77.  64.4 71.6]
 [75.2 64.4 69.8]]


In [28]:
scores = np.array([[85, 90, 78],
                   [92, 88, 95],
                   [80, 85, 82]])

In [31]:
# global statistics
print("Overall Highest Score:", np.max(scores))
print("Overall Lowest Score:", np.min(scores))
print("Overall Average Score:", np.mean(scores).round(2))

Overall Highest Score: 95
Overall Lowest Score: 78
Overall Average Score: 86.11


In [33]:
# Statistics by axis
# Average scores for each subject (axis 0)
subject_averages = np.mean(scores, axis=0).round(2)
print("Average Score for Each Subject:", subject_averages)

# Average scores for each student (axis 1)
student_averages = np.mean(scores, axis=1).round(2)
print("Average Score for Each Student:", student_averages)

Average Score for Each Subject: [85.67 87.67 85.  ]
Average Score for Each Student: [84.33 91.67 82.33]


**Python list vs Numpy array performance comparison**

In [ ]:
import time
size = 1_000_000
python_list = list(range(size))
numpy_array = np.arange(size)

In [49]:
start_time = time.time()
python_list_result = [x * 2 for x in python_list]
python_duration = time.time() - start_time
print(f"Python list processing time: {python_duration:.4f} seconds")

start_time = time.time()
numpy_result = numpy_array * 2
numpy_duration = time.time() - start_time
print(f"Numpy array processing time: {numpy_duration:.4f} seconds")

print(f"Numpy is approximately {python_duration / numpy_duration:.2f} times faster than Python list for this operation.")

Python list processing time: 0.0940 seconds
Numpy array processing time: 0.0043 seconds
Numpy is approximately 21.91 times faster than Python list for this operation.


**Scenario:** Create a numpy array cotaining numbers from 1 to 10, calculate and display the sum, mean, maximum value and minimun value of the array then reshape the array into a 2 x 5 matrix and add 5 to each element using numpy broadcasting. After that, extract all the even numbers from the original array using conditional filetering. Finally create two arrays a = [1, 2, 3] and b = [4, 5, 6] and perform element-wise addition, multiplication and dot product operation. Display the results of all computations with appropriate labels.

In [50]:
nums = np.arange(1, 11)
print("Original Array:", nums)

Original Array: [ 1  2  3  4  5  6  7  8  9 10]


In [51]:
print("Sum:", np.sum(nums))
print("Mean:", np.mean(nums))
print("Maximum Value:", np.max(nums))
print("Minimum Value:", np.min(nums))

Sum: 55
Mean: 5.5
Maximum Value: 10
Minimum Value: 1


In [52]:
nums_reshaped = nums.reshape(2, 5)

In [53]:
print("Added 5 to each element:")
print(nums_reshaped + 5)

Added 5 to each element:
[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [54]:
print("Even numbers in the original array:", nums[nums % 2 == 0])

Even numbers in the original array: [ 2  4  6  8 10]


In [57]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [58]:
print("Element-wise addition:", a+b)

Element-wise addition: [5 7 9]


In [59]:
print("Element-wise Multiplication", a*b)

Element-wise Multiplication [ 4 10 18]


In [60]:
print("Dot product operation:", a.dot(b))

Dot product operation: 32
