In [3]:
import numpy as np

**creating a 1D array from a list**

In [6]:
sales_list = [120, 150, 300, 250, 90]
sales_array = np.array(sales_list)
print(sales_list)
print(sales_array)

[120, 150, 300, 250, 90]
[120 150 300 250  90]


**creating a 2D array from a list of lists**

In [8]:
# features: [age, income_in_k, credit_score]

customer_matrix = np.array([[25, 50, 710],
                            [41, 95, 780],
                            [32, 65, 620]])

print(customer_matrix)

[[ 25  50 710]
 [ 41  95 780]
 [ 32  65 620]]


**creating a matrix of zeros**

In [9]:
zero_matrix = np.zeros((3, 4))
print(zero_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Arange function to create a sequenced array**

In [10]:
sequenced_array = np.arange(0,10,2)
print(sequenced_array)

[0 2 4 6 8]
