In [3]:
import numpy as np

**creating a 1D array from a list**

In [6]:
sales_list = [120, 150, 300, 250, 90]
sales_array = np.array(sales_list)
print(sales_list)
print(sales_array)

[120, 150, 300, 250, 90]
[120 150 300 250  90]


**creating a 2D array from a list of lists**

In [11]:
# features: [age, income_in_k, credit_score]

customer_matrix = np.array([[25, 50, 710],
                            [41, 95, 780],
                            [32, 65, 620]])

print(customer_matrix)
print("Customer matrix shape:", customer_matrix.shape)

[[ 25  50 710]
 [ 41  95 780]
 [ 32  65 620]]
Customer matrix shape: (3, 3)


**creating a matrix of zeros**

In [ ]:
zero_matrix = np.zeros((3, 4))
print(zero_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Arange function to create a sequenced array**

In [10]:
sequenced_array = np.arange(0,10,2)
print(sequenced_array)

[0 2 4 6 8]


**Slicing a 1D array**

In [13]:
traffic = np.array([500, 600, 550, 700, 650, 900, 1100])
weekend_traffic = traffic[-2:]
print(weekend_traffic)

[ 900 1100]


**Setup a 2D array to represent sensor readings**

In [ ]:
sensors = np.array([
            [12.1,14.3,15.2],#sensor 0
            [11.5,13.8,14.9],#sensor 1
            [10.8,12.5,13.7],#sensor 2
            [9.5,11.2,12.4] #sensor 3
        ])

In [16]:
sensors

array([[12.1, 14.3, 15.2],
       [11.5, 13.8, 14.9],
       [10.8, 12.5, 13.7],
       [ 9.5, 11.2, 12.4]])

In [19]:
specific_reading = sensors[2, 1]
print(specific_reading)

12.5


In [20]:
top_sensors = sensors[0:2, :]
print(top_sensors)

[[12.1 14.3 15.2]
 [11.5 13.8 14.9]]
